name: Deploy Thermostat to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # opcional, si necesitás todo el historial para alguna razón

      - name: Install backend dependencies
        run: |
          set -e
          cd backend
          sudo npm ci

      - name: Build backend
        run: |
          set -e
          cd backend
          npm run build
          echo "✅ Backend construido correctamente"

      - name: Configure pigpio daemon
        run: |
          echo "Configurando daemon de pigpio..."
          # Verificar si pigpio está instalado, instalarlo si es necesario
          if ! dpkg -l | grep -q pigpio; then
            echo "Instalando pigpio..."
            sudo apt-get update
            sudo apt-get install -y pigpio
          fi
          
          # Verificar si el daemon ya está en ejecución
          DAEMON_RUNNING=0
          if pgrep pigpiod > /dev/null; then
            echo "Daemon pigpio ya está en ejecución"
            # Verificar cuántas instancias están corriendo
            DAEMON_COUNT=$(pgrep pigpiod | wc -l)
            if [ $DAEMON_COUNT -gt 1 ]; then
              echo "⚠️ Se detectaron $DAEMON_COUNT instancias del daemon pigpio - deteniendo todas las instancias"
              sudo killall pigpiod
              sleep 2
              DAEMON_RUNNING=0
            else
              DAEMON_RUNNING=1
            fi
          fi
          
          # Solo iniciar el daemon si no está corriendo ya
          if [ $DAEMON_RUNNING -eq 0 ]; then
            echo "Iniciando daemon pigpio..."
            sudo pigpiod -l -m -n 200
            sleep 2
            
            # Verificar que el daemon se inició correctamente
            if pgrep pigpiod > /dev/null; then
              echo "✅ Daemon pigpio iniciado correctamente"
            else
              echo "❌ Error: No se pudo iniciar el daemon de pigpio"
              exit 1
            fi
          fi

      - name: Configure GPIO and 1-Wire permissions
        run: |
          # Configurar permisos para GPIO
          if [ -d "/sys/class/gpio" ]; then
            sudo chown -R root:root /sys/class/gpio || true
            sudo chmod -R 777 /sys/class/gpio || true
            echo "✅ Permisos GPIO configurados correctamente"
          else
            echo "⚠️ Directorio GPIO no encontrado"
          fi
          
          # Configurar permisos para 1-Wire (sensores de temperatura)
          if [ -d "/sys/bus/w1/devices" ]; then
            sudo chown -R root:root /sys/bus/w1/devices || true
            sudo chmod -R 777 /sys/bus/w1/devices || true
            echo "✅ Permisos 1-Wire configurados correctamente"
          else
            echo "⚠️ Directorio 1-Wire no encontrado"
          fi

      - name: Restart backend with PM2
        run: |
          cd backend
          # Detener la aplicación anterior si está en ejecución
          sudo pm2 stop thermostat-backend || true
          # Iniciar o reiniciar con la configuración actualizada
          sudo pm2 startOrRestart ecosystem.config.js
          # Guardar la configuración para que sobreviva a reinicios
          sudo pm2 save

      - name: Install frontend dependencies
        run: |
          set -e
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          set -e
          cd frontend
          npm run build

      - name: Deploy frontend to Nginx folder
        run: |
          set -e
          sudo rm -rf /var/www/thermostat-frontend
          sudo cp -r frontend/dist /var/www/thermostat-frontend
          sudo systemctl restart nginx
