name: Deploy Thermostat to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # opcional, si necesitás todo el historial para alguna razón

      - name: Install backend dependencies
        run: |
          set -e
          cd backend
          sudo npm ci

      - name: Build backend
        run: |
          set -e
          cd backend
          npm run build

      - name: Install and initialize pigpio
        run: |
          # Instalar pigpio a nivel de sistema si no está instalado
          if ! dpkg -l | grep -q pigpio; then
            sudo apt-get update
            sudo apt-get install -y pigpio
          fi
          
          # Detener cualquier instancia existente del daemon de pigpio
          sudo killall pigpiod || true
          
          # Iniciar el daemon de pigpio con permisos adecuados
          sudo pigpiod -l -m -n 200
          
          # Esperar a que el daemon inicie completamente
          sleep 2
          
          # Comprobar que el daemon está funcionando
          if pgrep pigpiod > /dev/null; then
            echo "✅ Daemon pigpio iniciado correctamente"
          else
            echo "❌ Error: El daemon pigpio no pudo iniciarse"
            exit 1
          fi
          
          # Instalar pigpio para el usuario root (usado por sudo pm2)
          if ! sudo npm list -g pigpio &> /dev/null; then
            sudo npm install -g pigpio
          fi
          
          # También instalar localmente en la aplicación
          cd backend
          sudo npm install --no-save pigpio
          
          echo "✅ pigpio configurado correctamente"

      - name: Configure GPIO and 1-Wire permissions
        run: |
          # Configurar permisos para GPIO
          if [ -d "/sys/class/gpio" ]; then
            sudo chown -R root:root /sys/class/gpio || true
            sudo chmod -R 777 /sys/class/gpio || true
            echo "✅ Permisos GPIO configurados correctamente"
          else
            echo "⚠️ Directorio GPIO no encontrado - usando modo simulación"
          fi
          
          # Configurar permisos para 1-Wire (sensores de temperatura)
          if [ -d "/sys/bus/w1/devices" ]; then
            sudo chown -R root:root /sys/bus/w1/devices || true
            sudo chmod -R 777 /sys/bus/w1/devices || true
            echo "✅ Permisos 1-Wire configurados correctamente"
          else
            echo "⚠️ Directorio 1-Wire no encontrado - usando modo simulación"
          fi

      - name: Restart backend with PM2
        run: |
          cd backend
          # Detener la aplicación anterior si está en ejecución
          sudo pm2 stop thermostat-backend || true
          # Iniciar o reiniciar con la configuración actualizada
          sudo pm2 startOrRestart ecosystem.config.js
          # Guardar la configuración para que sobreviva a reinicios
          sudo pm2 save

      - name: Install frontend dependencies
        run: |
          set -e
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          set -e
          cd frontend
          npm run build

      - name: Deploy frontend to Nginx folder
        run: |
          set -e
          sudo rm -rf /var/www/thermostat-frontend
          sudo cp -r frontend/dist /var/www/thermostat-frontend
          sudo systemctl restart nginx
