name: Deploy Thermostat to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: git pull origin main

      - name: Install backend dependencies
        run: |
          cd backend/src
          npm ci

      - name: Build backend
        run: |
          cd backend/src
          npm run build

      - name: Restart backend with PM2
        run: pm2 restart thermostat-backend
