name: Deploy Thermostat on Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (si hace falta)
        run: |
          npm install  # o pnpm install o yarn según uses

      - name: Build app (si aplica)
        run: |
          npm run build

      - name: Run deploy script
        run: |
          chmod +x ./deploy/deploy.sh
          ./deploy/deploy.sh
